import { StyleSheet, Platform } from "react-native";
import { COLORS } from "./colors";

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: COLORS.bg,
    paddingTop: Platform.OS === "android" ? 8 : 0,
  },
  flex: { flex: 1 },
  scrollContent: { paddingHorizontal: 18, paddingTop: 12, paddingBottom: 105 },
  formContent: { paddingHorizontal: 18, paddingTop: 12, paddingBottom: 110 },
  logo: { flexDirection: "row", alignItems: "center", gap: 8 },
  logoSmall: { flexDirection: "row", alignItems: "center" },
  logoMark: {
    width: 28,
    height: 28,
    borderRadius: 9,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  logoMarkText: { color: "#fff", fontSize: 18, fontWeight: "800" },
  logoText: { fontSize: 21, fontWeight: "800", color: COLORS.text },
  homeTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 18,
  },
  eyebrow: {
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 1.2,
    color: COLORS.primary,
    marginBottom: 3,
  },
  greeting: { fontSize: 20, fontWeight: "800", color: COLORS.text },
  homeQuestion: { fontSize: 12, color: COLORS.muted, marginTop: 3 },
  avatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#D9A66D",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#fff",
  },
  avatarText: { color: "#fff", fontWeight: "800", fontSize: 17 },
  searchFake: {
    height: 46,
    borderRadius: 12,
    backgroundColor: "#F4EEE8",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    gap: 8,
    marginBottom: 20,
  },
  searchPlaceholder: { color: COLORS.muted, fontSize: 12 },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 4,
    marginBottom: 11,
  },
  sectionTitle: { fontSize: 15, fontWeight: "800", color: COLORS.text },
  seeAll: { fontSize: 11, fontWeight: "700", color: COLORS.primary },
  categoryPill: {
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 14,
    paddingVertical: 9,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  categoryEmoji: { fontSize: 15 },
  categoryText: { fontSize: 11, fontWeight: "700", color: COLORS.text },
  recipeCard: {
    backgroundColor: COLORS.card,
    borderRadius: 15,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#F0E7E0",
    marginBottom: 12,
  },
  recipeImage: { width: "100%", height: 126 },
  recipeCardBody: { padding: 10 },
  cardTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 3,
  },
  categoryLabel: {
    fontSize: 9,
    fontWeight: "800",
    color: COLORS.primary,
    textTransform: "uppercase",
  },
  recipeTitle: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "800",
    color: COLORS.text,
  },
  metaRow: { flexDirection: "row", alignItems: "center", gap: 4, marginTop: 7 },
  metaText: { fontSize: 9.5, color: COLORS.muted },
  dot: { color: COLORS.muted, marginHorizontal: 1 },
  authorText: { fontSize: 9, color: COLORS.muted, marginTop: 5 },
  recipeCardHorizontal: { flexDirection: "row", minHeight: 95 },
  recipeImageHorizontal: { width: 105, height: 95 },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
    minHeight: 45,
  },
  headerLeft: { flexDirection: "row", alignItems: "center", gap: 7 },
  backButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: COLORS.card,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: COLORS.line,
  },
  screenTitle: { fontSize: 19, fontWeight: "800", color: COLORS.text },
  iconButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.94)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: COLORS.line,
  },
  iconButtonActive: { backgroundColor: COLORS.soft },
  searchInputWrap: {
    height: 46,
    backgroundColor: "#F4EEE8",
    borderRadius: 12,
    paddingHorizontal: 13,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  searchInput: { flex: 1, fontSize: 12, color: COLORS.text },
  filterPill: {
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 20,
    paddingHorizontal: 13,
    paddingVertical: 8,
    backgroundColor: COLORS.card,
  },
  filterPillActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  filterText: { fontSize: 10, fontWeight: "700", color: COLORS.text },
  filterTextActive: { color: "#fff" },
  resultCount: { fontSize: 11, color: COLORS.muted, marginBottom: 10 },
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 28,
    paddingVertical: 60,
  },
  emptyEmoji: { fontSize: 42, marginBottom: 10 },
  emptyIconCircle: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: COLORS.soft,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: COLORS.text,
    textAlign: "center",
  },
  emptyText: {
    fontSize: 12,
    color: COLORS.muted,
    textAlign: "center",
    marginTop: 6,
    lineHeight: 18,
  },
  secondaryButton: {
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 11,
    marginTop: 18,
  },
  secondaryButtonText: {
    color: COLORS.primary,
    fontWeight: "800",
    fontSize: 12,
  },
  detailImageWrap: { height: 305, position: "relative" },
  detailImage: { width: "100%", height: "100%" },
  detailTopButtons: {
    position: "absolute",
    top: 12,
    left: 14,
    right: 14,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  detailContent: {
    backgroundColor: COLORS.bg,
    marginTop: -12,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    padding: 18,
  },
  detailCategory: {
    color: COLORS.primary,
    fontWeight: "800",
    fontSize: 10,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  detailTitle: {
    color: COLORS.text,
    fontWeight: "900",
    fontSize: 24,
    lineHeight: 29,
    marginTop: 4,
  },
  detailAuthor: { color: COLORS.muted, fontSize: 10, marginTop: 6 },
  detailMetaGrid: { flexDirection: "row", gap: 8, marginTop: 16 },
  metaBox: {
    flex: 1,
    backgroundColor: COLORS.card,
    borderRadius: 13,
    paddingVertical: 10,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.line,
  },
  metaBoxValue: {
    fontSize: 10,
    fontWeight: "800",
    color: COLORS.text,
    marginTop: 4,
  },
  metaBoxLabel: { fontSize: 8, color: COLORS.muted, marginTop: 2 },
  tabRow: {
    flexDirection: "row",
    gap: 28,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.line,
    marginTop: 20,
  },
  detailTab: {
    paddingBottom: 10,
    color: COLORS.muted,
    fontSize: 12,
    fontWeight: "700",
  },
  detailTabActive: {
    color: COLORS.primary,
    borderBottomWidth: 2,
    borderBottomColor: COLORS.primary,
  },
  detailSectionTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: COLORS.text,
    marginTop: 17,
    marginBottom: 9,
  },
  ingredientRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    marginBottom: 9,
  },
  checkCircle: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  ingredientText: { flex: 1, fontSize: 11, color: COLORS.text },
  stepRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 12,
    alignItems: "flex-start",
  },
  stepNumber: {
    width: 23,
    height: 23,
    borderRadius: 12,
    backgroundColor: "#F7D8CD",
    alignItems: "center",
    justifyContent: "center",
  },
  stepNumberText: {
    color: COLORS.primaryDark,
    fontSize: 10,
    fontWeight: "900",
  },
  stepText: { flex: 1, fontSize: 11, lineHeight: 17, color: COLORS.text },
  primaryButton: {
    height: 48,
    borderRadius: 13,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    marginTop: 18,
  },
  primaryButtonText: { color: "#fff", fontSize: 13, fontWeight: "900" },
  formHint: {
    fontSize: 11,
    color: COLORS.muted,
    marginTop: -9,
    marginBottom: 13,
  },
  photoUpload: {
    height: 125,
    borderRadius: 13,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#F1A28F",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFBF8",
    marginBottom: 17,
  },
  uploadText: {
    color: COLORS.text,
    fontSize: 11,
    fontWeight: "800",
    marginTop: 6,
  },
  uploadHint: { color: COLORS.muted, fontSize: 9, marginTop: 2 },
  fieldWrap: { marginBottom: 13 },
  fieldLabel: {
    fontSize: 10,
    color: COLORS.text,
    fontWeight: "800",
    marginBottom: 6,
  },
  fieldInput: {
    minHeight: 43,
    borderWidth: 1,
    borderColor: COLORS.line,
    backgroundColor: COLORS.card,
    borderRadius: 10,
    paddingHorizontal: 12,
    fontSize: 11,
    color: COLORS.text,
  },
  fieldMultiline: { height: 75, paddingTop: 11, textAlignVertical: "top" },
  twoFields: { flexDirection: "row", gap: 10 },
  formSectionTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: COLORS.text,
    marginTop: 3,
    marginBottom: 8,
  },
  addRow: { flexDirection: "row", gap: 8, marginBottom: 7 },
  addInput: {
    flex: 1,
    height: 42,
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 10,
    backgroundColor: COLORS.card,
    paddingHorizontal: 12,
    fontSize: 11,
    color: COLORS.text,
  },
  addButton: {
    width: 42,
    height: 42,
    borderRadius: 10,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  addedItem: {
    fontSize: 10,
    color: COLORS.text,
    paddingVertical: 3,
    paddingLeft: 4,
  },
  profileHero: { alignItems: "center", paddingVertical: 4 },
  profileAvatar: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: "#C9945D",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: "#fff",
  },
  profileAvatarText: { color: "#fff", fontSize: 28, fontWeight: "900" },
  profileName: {
    fontSize: 20,
    fontWeight: "900",
    color: COLORS.text,
    marginTop: 8,
  },
  profileBio: {
    color: COLORS.muted,
    fontSize: 10,
    textAlign: "center",
    lineHeight: 15,
    maxWidth: 300,
    marginTop: 5,
  },
  outlineButton: {
    height: 37,
    borderWidth: 1,
    borderColor: COLORS.text,
    borderRadius: 20,
    paddingHorizontal: 24,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 11,
  },
  outlineButtonText: { fontSize: 10, fontWeight: "800", color: COLORS.text },
  statsRow: {
    flexDirection: "row",
    marginTop: 18,
    backgroundColor: COLORS.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.line,
    paddingVertical: 12,
  },
  stat: { flex: 1, alignItems: "center" },
  statValue: { fontSize: 14, fontWeight: "900", color: COLORS.text },
  statLabel: { fontSize: 9, color: COLORS.muted, marginTop: 2 },
  settingsCard: {
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 13,
    marginTop: 10,
  },
  settingsRow: {
    minHeight: 45,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    paddingHorizontal: 12,
  },
  settingsRowText: {
    flex: 1,
    fontSize: 11,
    fontWeight: "700",
    color: COLORS.text,
  },
  settingsGroup: {
    fontSize: 9,
    fontWeight: "900",
    color: COLORS.primary,
    letterSpacing: 1.1,
    marginTop: 7,
    marginBottom: 6,
  },
  settingsRowBox: {
    minHeight: 47,
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 11,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 7,
  },
  rowLeft: { flexDirection: "row", alignItems: "center", gap: 9, flex: 1 },
  rowRight: { flexDirection: "row", alignItems: "center", gap: 5 },
  settingsValue: { fontSize: 9, color: COLORS.muted },
  logoutButton: {
    height: 45,
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 12,
    marginTop: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  logoutText: { color: COLORS.primary, fontSize: 11, fontWeight: "800" },
  bottomNav: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 70,
    backgroundColor: "rgba(255,255,255,0.98)",
    borderTopWidth: 1,
    borderTopColor: COLORS.line,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    paddingHorizontal: 8,
  },
  navItem: {
    width: 58,
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
  },
  navLabel: { fontSize: 8.5, color: COLORS.muted, fontWeight: "600" },
  navLabelActive: { color: COLORS.primary, fontWeight: "800" },
  createNavButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    marginTop: -18,
    borderWidth: 4,
    borderColor: COLORS.bg,
  },
});
